jobs:
  test:
    docker:
      - image: adoptopenjdk/maven-openjdk11:latest
    steps:
      - checkout
      - run: mvn test

  build:
    docker:
      - image: adoptopenjdk/maven-openjdk11:latest
    steps:
      - checkout
      - run: mvn -Dmaven.test.skip=true package

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build